/**
 * The session, and the API that carries it.
 *
 * Everything hard here lives in @astratra/native and @astratra/client: the
 * keystore contract, the single-flight refresh, the replay-once rule. This
 * file only says WHICH keystore, WHICH base URL, and what to do when a session
 * finally expires.
 */
import { Platform } from 'react-native';
import * as SecureStore from 'expo-secure-store';
import Constants from 'expo-constants';
import { createApiClient, createSecureSession, createWebKeystore } from '@astratra/native';
import i18n from '../i18n/config';

/** Change this once, here. Everything else reads it from the session module. */
export const NAMESPACE = 'astratra';

/* The Android emulator lives in its own network VM: "localhost" there means
   the emulator itself, not the machine running the API. 10.0.2.2 is the
   standard alias back to the host. The iOS simulator shares the Mac's network
   and needs no such trick. */
const DEV_HOST = Platform.OS === 'android' ? '10.0.2.2' : 'localhost';

/* No `/api` suffix: the API generated by `--template api|fullstack` mounts its
   routes at the root (`/auth/login`, `/users`, …). Point this at whatever your
   server actually serves — EXPO_PUBLIC_API_BASE_URL wins over the default. */
export const API_BASE_URL = String(
  Constants.expoConfig?.extra?.apiBaseUrl
  || process.env.EXPO_PUBLIC_API_BASE_URL
  || `http://${DEV_HOST}:3000`
);

/* expo-secure-store has no real web implementation. localStorage is NOT a
   keystore — it is here so a browser preview can be clicked through in
   development, never to hold a session in a shipped build. */
const keystore = Platform.OS === 'web'
  ? createWebKeystore(typeof localStorage === 'undefined' ? null : localStorage)
  : SecureStore;

export const session = createSecureSession({ keystore, namespace: NAMESPACE });

let onExpired: () => void = () => {};

/** Called by the auth context once it knows how to route to the sign-in screen. */
export function onSessionExpired(handler: () => void) {
  onExpired = handler;
}

async function refresh() {
  const refreshToken = await session.getRefreshToken();
  if (!refreshToken) throw new Error('NO_REFRESH_TOKEN');

  const response = await fetch(`${API_BASE_URL}/auth/refresh`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ refreshToken })
  });
  if (!response.ok) throw new Error('REFRESH_FAILED');

  /* The server names the access token `token`, not `accessToken`. Reading the
     wrong field fails silently: the session is "saved" with undefined, and the
     next request goes out unauthenticated. */
  const payload = await response.json();
  await session.save({
    accessToken: payload?.data?.token,
    refreshToken: payload?.data?.refreshToken
  });
}

export const api = createApiClient({
  baseUrl: API_BASE_URL,
  session,
  refresh,
  /* Read per call, never cached: the person changes language without a restart. */
  language: () => String(i18n.language || '').slice(0, 2) || null,
  onSessionExpired: () => onExpired()
});
