/**
 * Notifications written by the server, in the recipient's language — and a
 * separate, NEUTRAL text for the lock screen.
 *
 * A notification generated by the server (a grade, an invoice, a result) is a
 * key and some parameters; the title and the message are rendered per
 * recipient, in their language. The texts are yours — this module holds none.
 *
 * The lesson that justifies a module rather than a dictionary: a push is shown
 * on a LOCKED screen, to whoever holds or glances at the phone. An end-of-year
 * decision about a child appeared there in full — under a title that had been
 * carefully made neutral, because the body was the message itself. So an
 * entry may declare `pushBody`: a neutral line ("Open the app to view it")
 * that replaces the message in the push only. The inbox, the screen and the
 * email — read in a personal mailbox, after unlocking — keep the full message.
 *
 * And the lesson that justifies `audit()`: a neutral push body declared in
 * one language and forgotten in another leaks in that other language only.
 * Nobody reading the catalogue in their own language will ever see it.
 */

const PLACEHOLDER_LEAK = /\b(undefined|null|NaN)\b|\[object Object\]/;

/**
 * @param {object} options
 * @param {string[]} options.languages
 * @param {string} [options.defaultLanguage] defaults to the first entry.
 * @param {object|object[]} options.entries key -> { language: render }, where
 *   render is `(params) => ({ title, message?, pushBody? })` or that object
 *   itself. Several objects (one per domain) are merged, and a key declared
 *   twice is an error at start-up — never a silent overwrite.
 */
function createNotificationCatalog(options = {}) {
  const languages = options.languages || [];
  if (!languages.length) throw new Error('createNotificationCatalog requires options.languages.');
  const defaultLanguage = options.defaultLanguage || languages[0];
  if (!languages.includes(defaultLanguage)) {
    throw new Error(`createNotificationCatalog: defaultLanguage "${defaultLanguage}" is not in options.languages.`);
  }
  const supported = new Set(languages);

  const entries = new Map();
  for (const group of [].concat(options.entries || [])) {
    for (const [key, byLanguage] of Object.entries(group || {})) {
      if (entries.has(key)) {
        throw new Error(`createNotificationCatalog: key "${key}" is declared twice.`);
      }
      if (!byLanguage || typeof byLanguage !== 'object') {
        throw new Error(`createNotificationCatalog: "${key}" must be an object keyed by language.`);
      }
      for (const language of Object.keys(byLanguage)) {
        if (!supported.has(language)) {
          throw new Error(`createNotificationCatalog: "${key}" declares unknown language "${language}".`);
        }
      }
      if (!byLanguage[defaultLanguage]) {
        /* The fallback of every other language: without it, a recipient in a
           half-filled language would get nothing at all. */
        throw new Error(`createNotificationCatalog: "${key}" has no "${defaultLanguage}" version.`);
      }
      entries.set(key, byLanguage);
    }
  }

  const base = (tag) => String(tag || '').trim().toLowerCase().split('-')[0];

  /**
   * @returns {{key: string, language: string, title: string, message: string,
   *   push: {title: string, body: string}, neutralPush: boolean}}
   *   `language` is the one actually rendered — the default when the requested
   *   one is missing. `push.body` is the neutral text when the entry has one,
   *   the message otherwise.
   * @throws on an unknown key: that is a typo in the code, and a notification
   *   with no text is worse than a failed call during development.
   */
  function render(key, language, params = {}) {
    const byLanguage = entries.get(key);
    if (!byLanguage) throw new Error(`Unknown notification key: ${key}`);

    const requested = base(language);
    const rendered = byLanguage[requested] ? requested : defaultLanguage;
    const template = byLanguage[rendered];
    const content = (typeof template === 'function' ? template(params || {}) : template) || {};

    const title = content.title === undefined || content.title === null ? '' : String(content.title);
    const message = content.message === undefined || content.message === null ? '' : String(content.message);
    const neutral = content.pushBody !== undefined && content.pushBody !== null;

    return {
      key,
      language: rendered,
      title,
      message,
      push: { title, body: neutral ? String(content.pushBody) : message },
      neutralPush: neutral
    };
  }

  /**
   * What would go wrong, found before a recipient finds it.
   *
   * @param {object} [auditOptions]
   * @param {Record<string, object>} [auditOptions.params] sample parameters
   *   per key, so templates render as they would in production.
   * @returns {{missing: Array<{key: string, language: string}>,
   *   pushBodyGaps: Array<{key: string, languages: string[]}>,
   *   placeholders: Array<{key: string, language: string, text: string}>,
   *   errors: Array<{key: string, language: string, error: string}>}}
   *   - missing: a language not written for a key (the default is served).
   *   - pushBodyGaps: a neutral push declared in some languages and not in
   *     others — the lock-screen leak nobody sees in their own language.
   *   - placeholders: "undefined", "null", "NaN" or "[object Object]" in a
   *     rendered text — a parameter the template expected and did not get.
   *   - errors: a template that throws on the sample parameters.
   */
  function audit(auditOptions = {}) {
    const samples = auditOptions.params || {};
    const report = { missing: [], pushBodyGaps: [], placeholders: [], errors: [] };

    for (const [key, byLanguage] of entries) {
      const withNeutral = [];
      const without = [];
      for (const language of languages) {
        if (!byLanguage[language]) {
          report.missing.push({ key, language });
          continue;
        }
        let rendered;
        try {
          rendered = render(key, language, samples[key] || {});
        } catch (error) {
          report.errors.push({ key, language, error: error.message });
          continue;
        }
        (rendered.neutralPush ? withNeutral : without).push(language);
        for (const text of [rendered.title, rendered.message, rendered.push.body]) {
          if (PLACEHOLDER_LEAK.test(text)) report.placeholders.push({ key, language, text });
        }
      }
      if (withNeutral.length && without.length) report.pushBodyGaps.push({ key, languages: without });
    }

    return report;
  }

  return {
    languages: [...languages],
    defaultLanguage,
    render,
    audit,
    has: (key) => entries.has(key),
    keys: () => [...entries.keys()]
  };
}

module.exports = { createNotificationCatalog };
